# fly.toml app configuration file generated for pii-guard on 2025-04-05T15:35:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pii-guard'
primary_region = 'fra'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'pii-guard.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false       
  auto_start_machines = true
  min_machines_running = 1         
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    method = "get"
    path = "/api/health"
    protocol = "http"
    timeout = "5s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
